stages:
  - test
  - test2

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "ext"

test:
  stage: test
  script:
    - echo 123
  tags:
    - instance
  when: manual

test2:
  stage: test2
  script:
    - echo 222
  tags:
    - instance
  when: manual
